#!/bin/bash

# Ensure timezone is configured properly
if [[ ! -z "$TZ" ]]; then
    if [[ -f /usr/share/zoneinfo/$TZ ]]; then
         ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
         echo "$TZ" >  /etc/timezone
    else
        echo "WARNING: $TZ is not a valid time zone."
    fi
fi

# Launch supervisord with configuration
supervisord -c /etc/supervisor.conf