#!/usr/bin/with-contenv bash

# we have to set it, otherwise chrome won't find ~/.asoundrc file
HOME=/home/jibri

DAEMON=/opt/jitsi/jibri/launch.sh
exec s6-setuidgid jibri /bin/bash -c "/usr/bin/first-start-chrome.sh && exec $DAEMON"
