name: Docker Publish Jitsi Component

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
    secrets:
      github-token:
        required: true

env:
  REGISTRY: ghcr.io
  REGISTRY_BASE_PATH: ghcr.io/${{ github.repository }}
  BASE_TAG: ${{ github.ref_name }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.github-token }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY_BASE_PATH }}/${{ inputs.folder }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: "${{ inputs.folder }}"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          "BASE_TAG=${{ env.BASE_TAG }}"
          "JITSI_REPO=${{ env.REGISTRY_BASE_PATH }}"
      if: contains(github.ref_name, '/merge') == false

    - name: Build and push Docker image for PR
      uses: docker/build-push-action@v4
      with:
        context: "${{ inputs.folder }}"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          "BASE_TAG=${{ github.base_ref }}"
          "JITSI_REPO=${{ env.REGISTRY_BASE_PATH }}"
      if: contains(github.ref_name, '/merge')
