name: Jitsi Meet Docker Images

on:
  push:
    branches: [ main, master, testing, openshift ]
    tags: [ 'stable-*-ems*', 'openshift-*-ems*' ]
  pull_request:
    branches: [ main, master, testing, openshift ]

jobs:
  build-push-base:
    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: base
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-base-java:
    needs:
    - build-push-base

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: base-java
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-jibri:
    needs:
    - build-push-base-java

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: jibri
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  
  build-push-jicofo:
    needs:
    - build-push-base-java

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: jicofo
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-jigasi:
    needs:
    - build-push-base-java

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: jigasi
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-jvb:
    needs:
    - build-push-base-java

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: jvb
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-prosody:
    needs:
    - build-push-base

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: prosody
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-web:
    needs:
    - build-push-base

    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: web
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-excalidraw:
    uses: ./.github/workflows/docker-publish-individual.yml
    with:
      folder: excalidraw-backend
      repository: jitsi/excalidraw-backend
      ref: "x21"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
